// ============================================================
//  course-data.js  –  Single source of truth for all courses
//  Used by: category page (script.js) AND course-page.js
// ============================================================

const coursesData = [
    // ── WRITING ────────────────────────────────────────────
    {
        id: 1,
        title: "IELTS Writing Task 2 Masterclass",
        author: "Sarah Mitchell",
        rating: 4.9, ratingCount: 3450,
        hours: 30, lectures: 210, level: "All Levels",
        price: 129.9, originalPrice: 259.9,
        chapters: 20, category: "writing",
        description: "Master IELTS Writing Task 2 with proven essay frameworks, band-descriptor analysis, and 50+ model answers. Taught by a former IELTS examiner with 10+ years' experience.",
        instructorTitle: "Former IELTS Examiner & Writing Coach",
        instructorReviews: "18,200",
        instructorStudents: "28,400",
        instructorCourses: "7",
        instructorBio: "Sarah Mitchell is a former British Council IELTS examiner who has assessed over 15,000 test papers. She now brings examiner-level insight to her students, helping them understand exactly what graders look for in Task 1 and Task 2 responses.",
        syllabus: [
            { title: "Introduction to IELTS Writing",        lessons: 5,  duration: "45 min" },
            { title: "Task 2 Essay Types & Structures",      lessons: 8,  duration: "1.5 hrs" },
            { title: "Vocabulary & Coherence Strategies",    lessons: 7,  duration: "1.2 hrs" },
            { title: "Grammar for Band 7+",                  lessons: 6,  duration: "1 hr" },
        ],
        reviews: [
            { name: "Minh Tran",   date: "15 Jan 2025", stars: 5, comment: "Sarah's examiner perspective is invaluable. I jumped from Band 5.5 to Band 7 in Task 2 after just 3 weeks. The model answers and feedback templates are outstanding." },
            { name: "Linh Pham",   date: "02 Feb 2025", stars: 5, comment: "Best IELTS Writing course I have ever taken. Clear explanations, real exam examples, and the weekly writing challenges kept me motivated throughout." },
            { name: "Duc Nguyen",  date: "28 Feb 2025", stars: 4, comment: "Extremely thorough content. I especially loved the section on coherence and cohesion — it helped me understand why my essays were losing marks." },
        ],
        faq: [
            { q: "Is this course suitable for beginners?",           a: "Yes! The course starts from Band 5 level and progresses to Band 8 strategies. No prior IELTS preparation is needed." },
            { q: "How long do I have access to the materials?",      a: "Lifetime access. Once enrolled, all videos, PDFs, and practice tasks are yours forever." },
            { q: "Does this course cover Task 1 as well?",           a: "This course focuses on Task 2. We have a separate dedicated Task 1 course available on BandPath." },
            { q: "Will I receive a certificate on completion?",      a: "Yes, a BandPath Certificate of Completion is issued upon finishing all modules and the final assessment." },
        ],
    },
    {
        id: 2,
        title: "IELTS Writing Task 1 – Graphs & Charts",
        author: "Sarah Mitchell",
        rating: 4.8, ratingCount: 2100,
        hours: 18, lectures: 130, level: "Intermediate",
        price: 99.9, originalPrice: 199.9,
        chapters: 14, category: "writing",
        description: "Learn to describe bar charts, line graphs, pie charts, maps, and process diagrams with accuracy and clarity. Covers all Academic Task 1 question types with step-by-step band-score rubrics.",
        instructorTitle: "Former IELTS Examiner & Writing Coach",
        instructorReviews: "18,200", instructorStudents: "28,400", instructorCourses: "7",
        instructorBio: "Sarah Mitchell is a former British Council IELTS examiner with a decade of marking experience and a passion for making complex writing skills accessible to every learner.",
        syllabus: [
            { title: "Understanding Task 1 Question Types", lessons: 4, duration: "40 min" },
            { title: "Describing Trends & Comparisons",     lessons: 6, duration: "1 hr" },
            { title: "Maps, Diagrams & Processes",          lessons: 5, duration: "55 min" },
            { title: "Timing & Editing Strategies",         lessons: 3, duration: "30 min" },
        ],
        reviews: [
            { name: "Thu Ha",    date: "10 Mar 2025", stars: 5, comment: "I always dreaded Task 1 but this course made it so logical. The vocabulary lists for each chart type alone are worth the price." },
            { name: "An Nguyen", date: "20 Mar 2025", stars: 4, comment: "Clear, concise, and packed with examples. Improved my Task 1 band from 5.5 to 7 in one month." },
            { name: "Nam Le",    date: "01 Apr 2025", stars: 5, comment: "Sarah explains the overview paragraph in a way no other course does. That single tip moved my score up by 0.5 band." },
        ],
        faq: [
            { q: "Is this Academic or General Training Task 1?",  a: "This course covers Academic Task 1. General Training letter writing is covered in our separate General Training course." },
            { q: "How many practice tasks are included?",         a: "Over 40 timed practice tasks with model answers and annotated examiner feedback." },
        ],
    },
    {
        id: 3,
        title: "IELTS Academic Writing Band 7+ Guide",
        author: "Emily Nguyen",
        rating: 4.7, ratingCount: 1800,
        hours: 22, lectures: 160, level: "Intermediate",
        price: 109.9, originalPrice: 219.9,
        chapters: 17, category: "writing",
        description: "A comprehensive guide to achieving Band 7 or above in IELTS Academic Writing. Combines lexical resource training, grammatical accuracy drills, and timed writing practice.",
        instructorTitle: "Academic IELTS Trainer",
        instructorReviews: "12,500", instructorStudents: "18,700", instructorCourses: "5",
        instructorBio: "Emily Nguyen holds a Masters in Applied Linguistics from the University of Melbourne and has been coaching IELTS candidates across Vietnam and Australia for over 8 years.",
        syllabus: [
            { title: "Lexical Resource for Band 7+",              lessons: 5, duration: "50 min" },
            { title: "Grammatical Range & Accuracy",              lessons: 6, duration: "1 hr" },
            { title: "Task Achievement & Coherence",              lessons: 4, duration: "45 min" },
            { title: "Full Timed Mock Essays with Feedback",      lessons: 4, duration: "2 hrs" },
        ],
        reviews: [
            { name: "Hoang Long", date: "05 Apr 2025", stars: 5, comment: "Emily's lexical resource module is incredible. I now know exactly which vocabulary features examiners reward at Band 7 vs Band 6." },
            { name: "Mai Nguyen", date: "18 Apr 2025", stars: 4, comment: "Very detailed and practical. The grammar drills were tough but effective. I scored Band 7.5 in Writing on my real test!" },
            { name: "Tuan Anh",   date: "30 Apr 2025", stars: 5, comment: "Best investment I made for my IELTS prep. Emily explains everything with such clarity. Highly recommend." },
        ],
        faq: [
            { q: "What band score does this course target?",    a: "Band 7 to Band 8. If you are aiming for Band 6, we recommend starting with our Writing Task 2 Masterclass first." },
            { q: "Is there live feedback on my writing?",       a: "The course includes 3 marked writing submissions reviewed by Emily's teaching team within 5 business days." },
        ],
    },

    // ── SPEAKING ───────────────────────────────────────────
    {
        id: 4,
        title: "IELTS Speaking Band 7+ Blueprint",
        author: "James Whitfield",
        rating: 4.8, ratingCount: 2810,
        hours: 18, lectures: 140, level: "Intermediate",
        price: 109.9, originalPrice: 219.9,
        chapters: 16, category: "speaking",
        description: "Build unstoppable confidence for the IELTS Speaking test. Learn proven strategies for Parts 1, 2, and 3, and master the fluency, vocabulary, and pronunciation features examiners reward.",
        instructorTitle: "IELTS Speaking Coach & Accent Trainer",
        instructorReviews: "9,800", instructorStudents: "9,300", instructorCourses: "4",
        instructorBio: "James Whitfield is a British-born IELTS coach based in Hanoi with over 12 years of one-on-one coaching experience. He has helped hundreds of students transform from hesitant speakers to confident Band 8 performers.",
        syllabus: [
            { title: "IELTS Speaking Test Overview",              lessons: 3, duration: "30 min" },
            { title: "Part 1 – Everyday Topic Fluency",           lessons: 5, duration: "55 min" },
            { title: "Part 2 – Cue Card Structures & Delivery",   lessons: 5, duration: "1 hr" },
            { title: "Part 3 – Discussion & Opinion Strategies",  lessons: 5, duration: "1 hr" },
        ],
        reviews: [
            { name: "Duc Nguyen",  date: "12 Feb 2025", stars: 5, comment: "I was absolutely terrified of Part 3 before this course. James's discussion frameworks gave me a structure to fall back on and I scored Band 8 in Speaking!" },
            { name: "Lan Anh",     date: "25 Feb 2025", stars: 5, comment: "The pronunciation module alone is worth the entire course fee. My intonation and word stress improved noticeably after just two weeks." },
            { name: "Khanh Ly",    date: "10 Mar 2025", stars: 4, comment: "Very practical course. Lots of real mock interview videos. Would love even more Part 2 cue card examples but overall outstanding." },
        ],
        faq: [
            { q: "Do I need a speaking partner to practise?",    a: "No. The course includes AI-powered speaking practice tools and recorded model responses you can shadow independently." },
            { q: "How is pronunciation covered in the course?",  a: "There are 6 dedicated pronunciation lessons covering word stress, sentence rhythm, connected speech, and intonation patterns." },
        ],
    },
    {
        id: 5,
        title: "IELTS Speaking Part 2 Cue Cards Bootcamp",
        author: "James Whitfield",
        rating: 4.7, ratingCount: 1560,
        hours: 12, lectures: 95, level: "Beginner",
        price: 79.9, originalPrice: 159.9,
        chapters: 10, category: "speaking",
        description: "Master 60+ IELTS Speaking Part 2 cue cards with ready-to-use answer templates and vocabulary banks. Perfect for learners who want to maximise their Part 2 score quickly.",
        instructorTitle: "IELTS Speaking Coach & Accent Trainer",
        instructorReviews: "9,800", instructorStudents: "9,300", instructorCourses: "4",
        instructorBio: "James Whitfield is a British-born IELTS coach based in Hanoi with over 12 years of one-on-one coaching experience.",
        syllabus: [
            { title: "Part 2 Structure & Timing",          lessons: 3, duration: "25 min" },
            { title: "People & Places Topic Cards",        lessons: 3, duration: "35 min" },
            { title: "Events & Experiences Topic Cards",   lessons: 2, duration: "25 min" },
            { title: "Objects & Ideas Topic Cards",        lessons: 2, duration: "25 min" },
        ],
        reviews: [
            { name: "Phuong Anh", date: "08 Mar 2025", stars: 5, comment: "I went through 50 cue cards in two weeks thanks to this bootcamp. The template approach is genius — I never ran out of things to say." },
            { name: "Bao Chau",   date: "22 Mar 2025", stars: 4, comment: "Great variety of topics. The vocabulary banks for each category saved me hours of preparation time." },
            { name: "Viet Hung",  date: "05 Apr 2025", stars: 5, comment: "Short, focused, and highly effective. Perfect for busy professionals who only have 30 minutes a day to study." },
        ],
        faq: [
            { q: "Is this suitable if I have never taken IELTS before?",  a: "Yes, the bootcamp starts from scratch. You will learn Part 2 structure before diving into the topic cards." },
            { q: "Are the cue cards from real past tests?",               a: "All 60+ cards are based on real IELTS exam topics reported by test-takers worldwide from 2022 to 2025." },
        ],
    },
    {
        id: 6,
        title: "Fluent English for IELTS Speaking",
        author: "Anna Petrova",
        rating: 4.6, ratingCount: 1200,
        hours: 15, lectures: 110, level: "All Levels",
        price: 89.9, originalPrice: 179.9,
        chapters: 12, category: "speaking",
        description: "Develop natural, flowing English speech for the IELTS Speaking test. Focuses on connected speech, fillers, idiomatic expressions, and spontaneous speaking drills.",
        instructorTitle: "IELTS Listening & Speaking Trainer",
        instructorReviews: "6,200", instructorStudents: "5,900", instructorCourses: "3",
        instructorBio: "Anna Petrova is a CELTA-qualified EFL teacher from St Petersburg, now based in Ho Chi Minh City. She specialises in accent reduction and spontaneous speaking training for IELTS candidates.",
        syllabus: [
            { title: "Natural Speech Patterns & Fillers",   lessons: 4, duration: "40 min" },
            { title: "Idiomatic Expressions for IELTS",    lessons: 3, duration: "35 min" },
            { title: "Connected Speech Drills",            lessons: 3, duration: "30 min" },
            { title: "Mock Interview Practice Sessions",   lessons: 2, duration: "40 min" },
        ],
        reviews: [
            { name: "Thi Nhung", date: "14 Apr 2025", stars: 5, comment: "Anna's course helped me sound so much more natural. The connected speech drills are addictive and I noticed a real difference in my fluency within days." },
            { name: "Quoc Bao",  date: "28 Apr 2025", stars: 4, comment: "Great content on fillers and discourse markers. I used to freeze mid-sentence — now I can keep talking naturally while I think." },
            { name: "Hoa Tran",  date: "10 May 2025", stars: 5, comment: "The mock interview sessions at the end of each module are excellent. Watching the model vs weak responses side by side is incredibly instructive." },
        ],
        faq: [
            { q: "Will this course help with pronunciation?",  a: "Yes — connected speech, word stress, and intonation are all covered with audio and video demonstrations." },
            { q: "How is this different from the Blueprint?",  a: "This course focuses on natural fluency and spontaneous speech rather than exam strategy. Both complement each other perfectly." },
        ],
    },

    // ── READING ────────────────────────────────────────────
    {
        id: 7,
        title: "IELTS Reading Speed & Strategies",
        author: "David Chen",
        rating: 4.7, ratingCount: 1980,
        hours: 12, lectures: 95, level: "Beginner",
        price: 89.9, originalPrice: 179.9,
        chapters: 11, category: "reading",
        description: "Overcome slow reading speed and question confusion with this tactical IELTS Reading course. Learn skimming, scanning, and time-management strategies that work under exam pressure.",
        instructorTitle: "IELTS Reading & Vocabulary Specialist",
        instructorReviews: "7,800", instructorStudents: "7,100", instructorCourses: "4",
        instructorBio: "David Chen holds a PhD in English Linguistics from National Taiwan University and has been preparing IELTS candidates across Asia for over 9 years.",
        syllabus: [
            { title: "Understanding the Reading Test Format", lessons: 3, duration: "30 min" },
            { title: "Skimming & Scanning Techniques",        lessons: 3, duration: "35 min" },
            { title: "Question-Type Attack Strategies",       lessons: 3, duration: "40 min" },
            { title: "Timed Full Practice Tests",             lessons: 2, duration: "1.5 hrs" },
        ],
        reviews: [
            { name: "Thu Ha",    date: "20 Feb 2025", stars: 5, comment: "I finished all three sections with 8 minutes to spare after applying David's skimming method. I scored Band 8 in Reading — something I never imagined possible." },
            { name: "Ngoc Mai",  date: "03 Mar 2025", stars: 5, comment: "The True/False/Not Given strategy is explained so clearly here. I had been making careless mistakes and now I am consistent." },
            { name: "Trung Hieu",date: "15 Mar 2025", stars: 4, comment: "Very practical and no fluff. David gets straight to the strategies. The timed practice tests at the end are essential." },
        ],
        faq: [
            { q: "How long should I study per day?",              a: "We recommend 45–60 minutes daily. Consistency matters more than marathon sessions for reading speed improvement." },
            { q: "Does this cover both Academic and General?",    a: "Yes. The strategy modules apply to both test types. General Training Section 3 is specifically addressed." },
        ],
    },
    {
        id: 8,
        title: "IELTS Reading: True/False/Not Given Drills",
        author: "David Chen",
        rating: 4.6, ratingCount: 1340,
        hours: 10, lectures: 80, level: "Intermediate",
        price: 69.9, originalPrice: 139.9,
        chapters: 9, category: "reading",
        description: "The most-feared IELTS question type — demystified. Dozens of drills, logic frameworks, and real exam passages to help you distinguish T/F/NG and Y/N/NG with confidence.",
        instructorTitle: "IELTS Reading & Vocabulary Specialist",
        instructorReviews: "7,800", instructorStudents: "7,100", instructorCourses: "4",
        instructorBio: "David Chen holds a PhD in English Linguistics from National Taiwan University and has been preparing IELTS candidates across Asia for over 9 years.",
        syllabus: [
            { title: "True vs False vs Not Given — The Logic",  lessons: 3, duration: "30 min" },
            { title: "Yes/No/Not Given for Opinion Passages",   lessons: 2, duration: "25 min" },
            { title: "Drill Set A – Factual Passages",          lessons: 2, duration: "30 min" },
            { title: "Drill Set B – Opinion Passages",          lessons: 2, duration: "30 min" },
        ],
        reviews: [
            { name: "Bich Van",  date: "11 Mar 2025", stars: 5, comment: "I was consistently getting T/F/NG wrong. After 3 days of David's drills I understood the logic completely and stopped second-guessing." },
            { name: "Tuan Kiet", date: "24 Mar 2025", stars: 4, comment: "Short but highly focused. Exactly what I needed. The logic flow diagrams in Module 1 are brilliant." },
            { name: "Kim Oanh",  date: "06 Apr 2025", stars: 5, comment: "Best specialised course on BandPath. Every IELTS student should take this as a supplement to their main course." },
        ],
        faq: [
            { q: "Is prior IELTS knowledge required?",     a: "Basic familiarity with the IELTS Reading test is recommended. This course dives deep into one specific question type." },
            { q: "How many practice items are included?",  a: "Over 120 individual True/False/Not Given questions across 18 full passages." },
        ],
    },
    {
        id: 9,
        title: "Academic Reading Comprehension for IELTS",
        author: "Emily Nguyen",
        rating: 4.8, ratingCount: 2200,
        hours: 16, lectures: 120, level: "Intermediate",
        price: 99.9, originalPrice: 199.9,
        chapters: 13, category: "reading",
        description: "Build deep comprehension skills for dense academic texts. Covers all 13 IELTS Academic Reading question types with detailed walkthroughs, vocabulary expansion, and full mock passages.",
        instructorTitle: "Academic IELTS Trainer",
        instructorReviews: "12,500", instructorStudents: "18,700", instructorCourses: "5",
        instructorBio: "Emily Nguyen holds a Masters in Applied Linguistics from the University of Melbourne and has been coaching IELTS candidates for over 8 years.",
        syllabus: [
            { title: "Reading All 13 Question Types",        lessons: 4, duration: "50 min" },
            { title: "Vocabulary in Context Strategies",     lessons: 3, duration: "35 min" },
            { title: "Matching Headings & Information",      lessons: 3, duration: "40 min" },
            { title: "Full Academic Mock Tests + Review",    lessons: 3, duration: "1.5 hrs" },
        ],
        reviews: [
            { name: "Phuong Linh", date: "16 Apr 2025", stars: 5, comment: "The most systematic IELTS Reading course I have come across. Emily breaks down every question type with a clear attack method. Scored Band 8 Academic Reading!" },
            { name: "Minh Duc",    date: "28 Apr 2025", stars: 4, comment: "Matching headings was my nightmare. After Emily's module I actually enjoy it. Great explanations, great examples." },
            { name: "Xuan Hoa",    date: "10 May 2025", stars: 5, comment: "The vocabulary sections are a bonus I didn't expect. My general comprehension of academic English has genuinely improved." },
        ],
        faq: [
            { q: "Does this cover General Training Reading?",  a: "The skills taught transfer well to General Training but the passages and mock tests in this course are Academic only." },
            { q: "How often is new content added?",            a: "Emily adds new mock passages and vocabulary units every quarter to reflect current IELTS exam trends." },
        ],
    },

    // ── LISTENING ──────────────────────────────────────────
    {
        id: 10,
        title: "IELTS Listening: Sections 1–4 Full Prep",
        author: "Anna Petrova",
        rating: 4.8, ratingCount: 2600,
        hours: 14, lectures: 105, level: "All Levels",
        price: 94.9, originalPrice: 189.9,
        chapters: 12, category: "listening",
        description: "Comprehensive IELTS Listening preparation covering all four sections. Train your ear with authentic-style audio, note-taking techniques, and 10 full practice tests with answer keys.",
        instructorTitle: "IELTS Listening & Speaking Trainer",
        instructorReviews: "6,200", instructorStudents: "5,900", instructorCourses: "3",
        instructorBio: "Anna Petrova is a CELTA-qualified EFL teacher from St Petersburg, now based in Ho Chi Minh City. She specialises in accent training and listening comprehension for IELTS candidates.",
        syllabus: [
            { title: "Listening Test Format & Strategies",  lessons: 3, duration: "30 min" },
            { title: "Section 1 & 2 – Social Contexts",    lessons: 3, duration: "40 min" },
            { title: "Section 3 & 4 – Academic Contexts",  lessons: 4, duration: "50 min" },
            { title: "Full Practice Tests & Review",       lessons: 2, duration: "1.5 hrs" },
        ],
        reviews: [
            { name: "Hoa Nguyen",  date: "25 Jan 2025", stars: 5, comment: "Anna's note-taking system for Section 4 monologues is a game-changer. I went from missing half the answers to catching almost everything." },
            { name: "Tuan Long",   date: "08 Feb 2025", stars: 5, comment: "10 full practice tests is incredible value. The audio quality is excellent and the difficulty range is exactly right." },
            { name: "My Hanh",     date: "20 Feb 2025", stars: 4, comment: "Very thorough preparation. I appreciate that the accent variety is realistic — British, Australian, American all covered." },
        ],
        faq: [
            { q: "What accents are used in the audio materials?",  a: "Recordings include British, Australian, American, and Canadian accents to mirror real IELTS test conditions." },
            { q: "Can I download the audio files?",                a: "Yes, all audio files are available for offline download within the BandPath app." },
        ],
    },
    {
        id: 11,
        title: "IELTS Listening Shortcuts & Note-Taking",
        author: "Anna Petrova",
        rating: 4.7, ratingCount: 1450,
        hours: 10, lectures: 78, level: "Beginner",
        price: 69.9, originalPrice: 139.9,
        chapters: 9, category: "listening",
        description: "Learn the fastest note-taking and prediction techniques for IELTS Listening. Sharpen your ability to anticipate answers before the audio plays and avoid common traps.",
        instructorTitle: "IELTS Listening & Speaking Trainer",
        instructorReviews: "6,200", instructorStudents: "5,900", instructorCourses: "3",
        instructorBio: "Anna Petrova is a CELTA-qualified EFL teacher specialising in listening comprehension and speaking confidence for IELTS candidates.",
        syllabus: [
            { title: "Prediction Strategies Before Listening",    lessons: 3, duration: "30 min" },
            { title: "Abbreviation & Symbol Note-Taking",         lessons: 3, duration: "30 min" },
            { title: "Common Traps & Distractors",               lessons: 2, duration: "25 min" },
            { title: "Speed Drills & Timed Practice",            lessons: 1, duration: "20 min" },
        ],
        reviews: [
            { name: "Bao Ngoc",   date: "02 Mar 2025", stars: 5, comment: "The prediction strategy alone helped me gain 3 extra correct answers in my mock test. Simple but incredibly powerful." },
            { name: "Thanh Tam",  date: "15 Mar 2025", stars: 4, comment: "Love the trap identification module. I used to fall for distractors constantly — now I spot them before they happen." },
            { name: "Viet Anh",   date: "28 Mar 2025", stars: 5, comment: "Short and sharp. Finished in a weekend and immediately applied the techniques in a full practice test. My score jumped 0.5 bands." },
        ],
        faq: [
            { q: "Is this course enough on its own for Listening prep?",  a: "This course is best combined with our Full Listening Prep course. Together they cover strategy + extensive practice." },
            { q: "Are there exercises for each strategy?",                a: "Yes, every strategy module has 3–5 targeted exercises with instant answer feedback." },
        ],
    },
    {
        id: 12,
        title: "Accent Training for IELTS Listening",
        author: "James Whitfield",
        rating: 4.6, ratingCount: 980,
        hours: 8, lectures: 60, level: "Beginner",
        price: 49.9, originalPrice: 99.9,
        chapters: 7, category: "listening",
        description: "Train your ear to understand British, Australian, American, and New Zealand accents as used in the real IELTS Listening test. Includes focused accent-specific drills and vocabulary.",
        instructorTitle: "IELTS Speaking Coach & Accent Trainer",
        instructorReviews: "9,800", instructorStudents: "9,300", instructorCourses: "4",
        instructorBio: "James Whitfield is a British-born IELTS coach based in Hanoi specialising in accent familiarisation and spoken English comprehension.",
        syllabus: [
            { title: "Why Accents Matter in IELTS",            lessons: 2, duration: "20 min" },
            { title: "British & Australian Accent Drills",     lessons: 2, duration: "25 min" },
            { title: "American & NZ Accent Drills",            lessons: 2, duration: "25 min" },
            { title: "Mixed Accent Listening Challenges",      lessons: 1, duration: "20 min" },
        ],
        reviews: [
            { name: "Dieu Linh", date: "10 Apr 2025", stars: 5, comment: "Australian accents used to be impossible for me. After two sessions of James's drills I could follow along comfortably. Brilliant course." },
            { name: "Van Cuong", date: "22 Apr 2025", stars: 4, comment: "Very focused and no filler. If you struggle with specific accents this is the fastest fix I know of." },
            { name: "Hong Anh",  date: "04 May 2025", stars: 5, comment: "I wish I had found this course earlier. The mixed accent challenge at the end is tough but exactly what the real test throws at you." },
        ],
        faq: [
            { q: "Which accents are covered?",                    a: "British (RP and regional), Australian, American, and New Zealand accents — all four that appear in the IELTS Listening test." },
            { q: "Do I need any prior IELTS preparation?",        a: "No, this is standalone and suitable for complete beginners who just want to improve accent comprehension." },
        ],
    },

    // ── FULL COURSES ───────────────────────────────────────
    {
        id: 13,
        title: "Complete IELTS Academic Prep – Band 7+",
        author: "Emily Nguyen",
        rating: 4.9, ratingCount: 4200,
        hours: 45, lectures: 320, level: "All Levels",
        price: 189.9, originalPrice: 379.9,
        chapters: 30, category: "full",
        description: "The most complete IELTS Academic preparation course on BandPath. Covers all four skills — Listening, Reading, Writing, and Speaking — with 15 full mock tests, live Q&A sessions, and personalised score tracking.",
        instructorTitle: "Academic IELTS Trainer",
        instructorReviews: "12,500", instructorStudents: "18,700", instructorCourses: "5",
        instructorBio: "Emily Nguyen holds a Masters in Applied Linguistics from the University of Melbourne and has been coaching IELTS candidates across Vietnam and Australia for over 8 years.",
        syllabus: [
            { title: "IELTS Academic Overview & Study Plan",    lessons: 4,  duration: "45 min" },
            { title: "Listening – All Sections Full Coverage",  lessons: 8,  duration: "2 hrs" },
            { title: "Reading – All Question Types",            lessons: 8,  duration: "2 hrs" },
            { title: "Writing Task 1 & Task 2",                 lessons: 8,  duration: "2 hrs" },
        ],
        reviews: [
            { name: "Minh Tuan",  date: "28 Jan 2025", stars: 5, comment: "I took this course 8 weeks before my exam and scored Band 7.5 overall. The structured study plan and mock tests kept me on track the entire time." },
            { name: "Thuy Duong", date: "10 Feb 2025", stars: 5, comment: "Everything you need in one place. Emily's teaching is clear, motivating, and deeply practical. The live Q&A sessions were incredibly helpful." },
            { name: "Quang Vinh", date: "22 Feb 2025", stars: 5, comment: "15 full mock tests is an extraordinary amount of practice material. I felt completely prepared walking into the exam centre. Got Band 8!" },
        ],
        faq: [
            { q: "How long does it take to complete the course?",  a: "Most students complete the core content in 8–12 weeks studying 1–2 hours per day. The mock tests add additional time." },
            { q: "Are live sessions recorded?",                    a: "Yes, all live Q&A sessions are recorded and available for playback within 24 hours." },
            { q: "Is this suitable for General Training as well?", a: "Core skills modules apply to both test types. A General Training Writing supplement is included as a bonus." },
        ],
    },
    {
        id: 14,
        title: "IELTS General Training Full Course",
        author: "Sarah Mitchell",
        rating: 4.8, ratingCount: 3100,
        hours: 40, lectures: 280, level: "All Levels",
        price: 169.9, originalPrice: 339.9,
        chapters: 26, category: "full",
        description: "Complete IELTS General Training preparation for immigration and professional registration purposes. Covers all four skills with a special focus on General Training Reading and the Task 1 Letter.",
        instructorTitle: "Former IELTS Examiner & Writing Coach",
        instructorReviews: "18,200", instructorStudents: "28,400", instructorCourses: "7",
        instructorBio: "Sarah Mitchell is a former British Council IELTS examiner with a decade of marking experience and a passion for making complex writing skills accessible to every learner.",
        syllabus: [
            { title: "General Training Test Format Overview",   lessons: 3,  duration: "30 min" },
            { title: "GT Reading – Sections 1, 2 & 3",         lessons: 7,  duration: "1.5 hrs" },
            { title: "GT Writing – Formal & Informal Letters", lessons: 7,  duration: "1.5 hrs" },
            { title: "Listening & Speaking for GT",            lessons: 7,  duration: "1.5 hrs" },
        ],
        reviews: [
            { name: "Van Long",    date: "15 Mar 2025", stars: 5, comment: "I needed Band 7 for my Australian PR application and scored exactly that on my first attempt. Sarah's course was the only preparation I used." },
            { name: "Phuong Thao", date: "28 Mar 2025", stars: 5, comment: "The formal letter writing module is exceptional. I had no idea there were so many conventions I was missing. Scored Band 8 in Writing." },
            { name: "Thanh Binh",  date: "10 Apr 2025", stars: 4, comment: "Very comprehensive course. I particularly liked the way the GT Reading sections are compared to Academic to highlight the differences." },
        ],
        faq: [
            { q: "Is this course suitable for Canada PR applications?",  a: "Yes. IELTS General Training is accepted for Canadian Express Entry and Provincial Nominee Programs." },
            { q: "What band score does this course target?",             a: "The course targets Band 6.5 to Band 8, suitable for immigration, nursing registration, and skilled worker visas." },
        ],
    },
    {
        id: 15,
        title: "IELTS Band 6.5 to Band 8 Accelerator",
        author: "David Chen",
        rating: 4.7, ratingCount: 2400,
        hours: 35, lectures: 240, level: "Advanced",
        price: 159.9, originalPrice: 319.9,
        chapters: 24, category: "full",
        description: "An advanced accelerator programme for learners already scoring Band 6.5 who need to reach Band 7.5 or Band 8. Focuses on the specific errors that prevent intermediate learners from breaking through the plateau.",
        instructorTitle: "IELTS Reading & Vocabulary Specialist",
        instructorReviews: "7,800", instructorStudents: "7,100", instructorCourses: "4",
        instructorBio: "David Chen holds a PhD in English Linguistics from National Taiwan University and has been preparing IELTS candidates across Asia for over 9 years.",
        syllabus: [
            { title: "Diagnosing Your Band 6.5 Weaknesses",     lessons: 4, duration: "45 min" },
            { title: "High-Frequency Band 7–8 Vocabulary",      lessons: 6, duration: "1 hr" },
            { title: "Common Errors at Band 6.5 – All Skills",  lessons: 8, duration: "1.5 hrs" },
            { title: "Band 8 Strategies & Full Mock Tests",     lessons: 6, duration: "2 hrs" },
        ],
        reviews: [
            { name: "Hung Nguyen",  date: "20 Apr 2025", stars: 5, comment: "I was stuck at 6.5 for two attempts. David's error diagnosis module showed me exactly why — I had very specific, fixable habits. Scored Band 7.5 on my next attempt." },
            { name: "Kim Chi",      date: "02 May 2025", stars: 5, comment: "This course treats you like an adult learner. No hand-holding, just targeted, efficient practice on the areas that matter most at Band 7+." },
            { name: "Bao Tran",     date: "14 May 2025", stars: 4, comment: "The vocabulary module is the best I have seen — not just lists of words but contextualised usage across all four skills. Genuinely improved my range." },
        ],
        faq: [
            { q: "What score should I have before taking this course?",   a: "You should already be scoring consistently around Band 6.5 in practice tests before enrolling in this accelerator." },
            { q: "Is this Academic or General Training?",                 a: "The accelerator covers both test types. Separate Academic and General Training mock tests are included." },
        ],
    },
];